language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer update --no-interaction --prefer-dist

script:
    - phpunit